backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: reigate-delivers # Add Cloudinary name
    api_key: 951981925954365
    default_transformations:
      - - fetch_format: auto
          width: 500
          quality: 80
          crop: limit

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    format: "json"
    extension: "json"
    delete: true
    editor:
      preview: false
    folder: content/locations
    slug: "{{month}}-{{day}}-{{name}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Name", name: "name", widget: "string" } 
      - { label: "Cover Image", name: "cover", widget: "image", multiple: false }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Website URL", name: "website", widget: "string" }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
      - { label: "Instagram URL", name: "instagram", widget: "string", required: false }
      - { label: "Twitter URL", name: "twitter", widget: "string", required: false }
      - { label: "Owner", name: "owner", widget: "string" }
      - { label: "Biography", name: "bio", widget: "string" }
      - { label: "Headshot Image", name: "headshot", widget: "image", multiple: false }
